import Footer from './components/Footer'
import { Navigation } from './components/Navigation'
import { Asap } from 'next/font/google'
import './globals.css'

export const metadata = {
  title: 'Supermercado da Familia',
  description: 'Generated by Lucas Lessa',
}


const asap = Asap({ subsets: ['latin'] })

export default function RootLayout({ children }) {
  const navLinks = [
    {
      name: 'INÍCIO',
      href: '/',
    },
    {
      name: 'COMPRE ONLINE',
      href: '/compreonline',
    },
    {
      name: 'LOJA',
      href: '/lojas',
    },
    {
      name: 'OFERTAS',
      href: '/ofertas',
    },
    {
      name: 'CONTATO',
      href: '/contato',
    },
    {
      name: 'SOBRE',
      href: '/sobre',
    },
  ]

  return (
    <html lang="en" className="h-full">
      <body className={`flex flex-col h-full ${asap.className}`}>
        <header>
          <Navigation navLinks={navLinks} />
        </header>
        
        <main className="flex-1">
          {children}
        </main>

        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  )
}
